GET http://localhost:3001/api/notes
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Backend-coding is hard",
  "important": true
}

###
PUT http://localhost:3001/api/notes/673f473b984272c416bc9c68
Content-Type: application/json

{
  "content": "PHP is a language of Chaos",
  "important": true
}

